// <auto-generated />
namespace LogParser.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_type_of_logFileId_in_LogLine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_type_of_logFileId_in_LogLine));
        
        string IMigrationMetadata.Id
        {
            get { return "201901212109555_change_type_of_logFileId_in_LogLine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
