// <auto-generated />
namespace LogParser.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_local_setting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_local_setting));
        
        string IMigrationMetadata.Id
        {
            get { return "201902022334428_add_local_setting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
