// <auto-generated />
namespace LogParser.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_dates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_dates));
        
        string IMigrationMetadata.Id
        {
            get { return "201903270133070_change_dates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
