// <auto-generated />
namespace LogParser.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_file_ext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_file_ext));
        
        string IMigrationMetadata.Id
        {
            get { return "201903041603333_remove_file_ext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
